### ISSUE TITLE
Adding new negations

### ISSUE THREAD

**Issue by kafechew** [wooorm/retext-sentiment#2]
Originally, it is:

     function isNegation(node) {
         var value;

         value = node.toString().toLowerCase();

         if (
             value === 'not' ||
             value === 'neither' ||
             value === 'nor' ||
             /n['’]t/.test(value)
         ) {
             return true;
         }

         return false;
     }

I found more negations... 
for example, "please improve" is negative...
and tried to improve... 

     function isNegation(node) {
         var value;

         value = node.toString().toLowerCase();

         if (
             value === 'not' ||
             value === 'neither' ||
             value === 'nor' ||
             value === 'never' ||
             value === 'nobody' ||
             value === 'none' ||
             value === 'nothing' ||
             value === 'nowhere' ||
             value === 'few' ||
             value === 'hardly' ||
             value === 'little' ||
             value === 'rarely' ||
             value === 'scarcely' ||
             value === 'seldom' ||
             value === 'please' ||
             /n['’]t/.test(value)
         ) {
             return true;
         }

         return false;
     }

But failed. The result for 
"not good" = -3
"never good" = +3 (which should be -3)

Anything missed out?

**Comment by wooorm** [comment]
Not sure, maybe you [checked the word instead of the sentence](https://github.com/wooorm/retext-sentiment/blob/6cf4b35ab33ca019cc78daccd76c8caeabb3108f/index.js#L108)? I got them to work.

I really like your addition, however, before including all, here are some notes:

```text
// These are really great, thanks!
never good
nobody good
nothing good
nowhere good
hardly good
rarely good

// These are a bit harder, having "a few nice" things
// isn't really a negation (thus pretty bad) right?
// I think the below ones are a bit more ambiguous
few good (thing)
little good (thing)
scarcely good (thing)
seldom good (thing)

// A bit more ambiguous are the below ones, why did
// you add them? Do you have clear use cases where they
// are always a negation:
none
please
```

P.S. This tool is awesome for checking how a word is used in a sentence [here](http://sentence.yourdictionary.com/none).

**Comment by wooorm** [comment]
@kafechew Closing this due to no response. Feel free to reopen.
