### ISSUE TITLE
Adding to the sentiment list

### ISSUE THREAD

**Issue by molinto** [wooorm/retext-sentiment#3]
Hi, do I have to make a pull request to add to the sentiment data list?

New word is "ultimate".

Thanks
Sharry

**Comment by wooorm** [comment]
First of all, you can inject new values, or overwrite existing values, by passing an `inject` hash as the plugin’s options: See [API](https://github.com/wooorm/retext-sentiment#api).

The internal list is based on [afinn-111](https://github.com/wooorm/afinn-111/blob/master/data/afinn-111.json), which I guess is a frozen “standard”.

Given enough animo, I might be interested in adding another dataset too, however, for just one word and without scientific backing (what valence would you give `ultimate`?), I’d rather not.

Does that help?

**Comment by molinto** [comment]
Ok thanks dude
