### ISSUE TITLE
Cannot find ./index.json module

### ISSUE THREAD

**Issue by ksjung** [wooorm/retext-sentiment#4]
Not really sure what this is supposed to reference.

**Comment by wooorm** [comment]
Hi @ksjung, thanks for your issue. 🎉

I’m afraid I’m not following. Could you supply more information? Such as code that shows how you use this project; version numbers; error output; etcetera? Tip: [Contributing to Open Source](https://guides.github.com/activities/contributing-to-open-source/#contributing).

**Comment by eterna2** [comment]
[line 16](https://github.com/wooorm/retext-sentiment/blob/master/index.js)
`var polarities = require('./index.json');`

Your npm module did not include a default set of polarities word mapping aka 'index.json' does not exist in your repo.

**Comment by wooorm** [comment]
Thanks both! Closed by 6932894.
